
services:
  momentomori:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: momentomori-app
    ports:
      - "2129:2129"
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    networks:
      - momentomori-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  momentomori-network:
    driver: bridge
